### ISSUE TITLE
texpreview depreciated functions removed from package

### ISSUE THREAD

**Issue by yonicd** [jonocarroll/mathpix#10]
Hi

I pushed to CRAN a new version of texPreview that removes the older functions in the package (texPreview==>tex_preview). 

see [NEWS](https://github.com/yonicd/texPreview/blob/master/NEWS.md)

I got pinged by CRAN that mathpix is a revdep of texPreview and that you should update mathpix to accomodate the change in the dep new version.

From what I can see you would need to change [here](https://github.com/jonocarroll/mathpix/blob/master/R/connect.R#L234) and the links in the docs.

thanks

**Comment by jonocarroll** [comment]
Cheers for the heads up! I'll make the appropriate change and submit a new version.

**Comment by yonicd** [comment]
$20 a pop? Hehe
