### ISSUE TITLE
Are there plans to resubmit to CRAN?

### ISSUE THREAD

**Issue by wibeasley** [jonocarroll/mathpix#12]
I'm one of the maintainer of the [Web Tech task view](https://cran.r-project.org/view=WebTechnologies).  This package hasn't been on CRAN for 60+ days, apparently because [texPreview](https://cran.r-project.org/package=texPreview) was removed.

Do you have plans for the mathpix package or suggestions if mathpix should be described differently in the task view?  I don't see any activity in the [texPreview repo](https://github.com/yonicd/texPreview).

![image](https://github.com/jonocarroll/mathpix/assets/1372890/585bb5c9-f5e6-496d-95e5-d9b1ae369b2f)

![image](https://github.com/jonocarroll/mathpix/assets/1372890/e183bb08-32b2-4054-8070-5fbfe324a108)

https://github.com/cran-task-views/WebTechnologies/issues/520

**Comment by jonocarroll** [comment]
Hi, thanks for the ping. I do plan to resubmit, I just need to find the time.
