### ISSUE TITLE
Verbose Error messaging

### ISSUE THREAD

**Issue by HanjoStudy** [jonocarroll/mathpix#4]
Output of `mathpix()` should return appropriate errors from `httr::POST` call.

Example:
![math_hard](https://user-images.githubusercontent.com/12710800/31075455-e43116dc-a775-11e7-83c3-bd9d0b15311f.jpg)

Returns:
![response](https://user-images.githubusercontent.com/12710800/31075484-0a3ffe38-a776-11e7-9796-fd0d39ac6def.JPG)

When it should actually be returning:
![error](https://user-images.githubusercontent.com/12710800/31075500-234eff1e-a776-11e7-99ed-48e287ea7f0f.JPG)

Which is a strange error as the picture size isn't very large. I assume this message is saying- "math too hard, try easier equation please"

This output was obtained from:
```
app_id <- "jcarroll"
app_key <- "13f1584b2f9edb8220bf619c0b4e3d5a"
message(paste0("Using Mathpix APP_ID=", app_id))
url <- "https://api.mathpix.com/v3/latex"
body <- paste0("{\"url\": \"data:image/jpeg;base64, ", base64enc::base64encode("R/math_hard.jpg"), 
               "\" }")
safePOST <- purrr::safely(httr::POST)
res <- safePOST(url, httr::add_headers(app_id = app_id, 
                                       app_key = app_key), 
                httr::content_type_json(), body = body)
httr::content(res$result)
```

**Comment by Nicktz** [comment]
I receive the exact same error on my machine. Also failed when trying to use it on a (very neatly, might I add) hand-written equation. I also agree with @HanjoStudy, for this package to go from nice to INSANE it would have to handle hard math as well :)

**Comment by jonocarroll** [comment]
Cheers for the heads up! I'm not sure that it's a 'math too hard' issue or even that the filesize is an issue, but it's cropping up frequently enough that I'll address it for sure. I have flagged this as something to look into, maybe pre-processing the images could help (#3). Some useful error messages would certainly be a great addition.

**Comment by jonocarroll** [comment]
I'm looking into this and (disregard previous comment). Now I see that the connection *does* work, but the response itself has an internal error result with the message you see. Thank you; I'll explicitly test for this.
