### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by ChristophHanck** [jonocarroll/mathpix#5]
Running an example of my own with a PNG (file attached, but same issue with jpg) as in 

```
library(mathpix)
mathpix(img="e:/dropbox/programmieren/R/GMM.png")
```
just returns an "empty" LaTeX display

$$
  
$$

The example file from the package works, though.

![gmm](https://user-images.githubusercontent.com/10358251/31656577-42497a5e-b32c-11e7-9ef2-d37b0a9c07df.PNG)

**Comment by jonocarroll** [comment]
Cheers, and yeah, this is a known thing (#4 and #3). I'm working on doing some pre-processing to raise the probability of success. I'm not yet sure what the reasoning behind the empty result is, but I've had some success via taking a screenshot of the image and trying that.
