### ISSUE TITLE
mathpix couldn't parse these images

### ISSUE THREAD

**Issue by tungttnguyen** [jonocarroll/mathpix#6]
I tried `mathpix` with these images but it didn't work

`library(mathpix)`   

`mathpix("./formula_01.png")`   

`mathpix("./formula_02.png")`

![formula_01](https://user-images.githubusercontent.com/6590141/31727502-93f3be98-b3de-11e7-8ac4-2df07e1d2711.png)
![formula_02](https://user-images.githubusercontent.com/6590141/31727503-940f56ee-b3de-11e7-8963-6cbde078b59a.png)

**Comment by jonocarroll** [comment]
Have another go... the backend seems to have had some improvements. These work now, I believe.

**Comment by tungttnguyen** [comment]
Yes working as expected now. Thanks for helping!
