### ISSUE TITLE
.deb/PPA please?

### ISSUE THREAD

**Issue by BloodyIron** [jonocarroll/mathpix#8]
Any chance we can get .deb builds for this? and/or a PPA/repo going on? :)

Snap doesn't work for how everyone managers their system ;)

Thanks! :D

**Comment by jonocarroll** [comment]
This is an R package - are you looking for something else?

**Comment by BloodyIron** [comment]
I misjudged the scope of this repo, sorry! I thought this was the main repo for mathpix.
